//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Post_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Post()
        {
            this.tbl_Comment = new HashSet<tbl_Comment>();
        }
    
        public long PostId { get; set; }
        public string PostName { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public long UserId { get; set; }
        public Nullable<int> TotalComments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Comment> tbl_Comment { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
